# Generated by Django 3.2.3 on 2021-05-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Password_Generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='id',
        ),
        migrations.AlterField(
            model_name='registration',
            name='Email',
            field=models.EmailField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
